### ISSUE TITLE
java.lang.NoClassDefFoundError found in kitkat while using android-job 

### ISSUE THREAD

**Issue by jsu4650** [vRallev/cat#2]
I am using android-job 1.1.7 in my app and I have tested my app in Nougat, MarshMallow and  Lollipop, It worked fine while testing the same apk in kikat it crashed raising this stackTrace

E/AndroidRuntime( 3208): java.lang.NoClassDefFoundError: net/vrallev/android/cat/CatUtil
E/AndroidRuntime( 3208): 	at net.vrallev.android.cat.CatGlobal.getDefaultCatLog(CatGlobal.java:83)
E/AndroidRuntime( 3208): 	at net.vrallev.android.cat.Cat.w(Cat.java:50)
E/AndroidRuntime( 3208): 	at com.evernote.android.job.util.GcmAvailableHelper.isGcmApiSupported(GcmAvailableHelper.java:55)
E/AndroidRuntime( 3208): 	at com.evernote.android.job.util.JobApi.isSupported(JobApi.java:99)
E/AndroidRuntime( 3208): 	at com.evernote.android.job.util.JobApi.getDefault(JobApi.java:147)
E/AndroidRuntime( 3208): 	at com.evernote.android.job.JobManager.<init>(JobManager.java:189)
E/AndroidRuntime( 3208): 	at com.evernote.android.job.JobManager.create(JobManager.java:114)

**Comment by vRallev** [comment]
That could have many reasons, e.g. it could be a multidex issue or you excluded the dependency for some reason? Hard to say, but Stackoverflow is a better place to ask such questions.
